### ISSUE TITLE
[Org] RPTU Kaiserslautern-Landau

### ISSUE THREAD

**Issue by ThorstenMichels** [eduMFA/Web#127]
{
  "name": "RPTU Kaiserslautern-Landau",
  "logoSrc": "![RPTU Logo_1c-1](https://github.com/user-attachments/assets/d7106bb6-eab7-4fd7-9998-02b189b3d25e)",
  "url": "https://rptu.de",
  "userCount": 23000,
  "phase": "Testing",
  "tokenTypes": [
    "IndexedSecret",
    "TOTP",
    "WebAuthn"
  ]
}

**Comment by Luc1412** [comment]
Thank you for your submission. Could you please open an issue with the Create or Update an Organization template. This will automatically open a pull request adding your org.

**Comment by Luc1412** [comment]
@ThorstenMichels I created an issue for you and added your org. Currently you don't provide a eduMFA enrolled user count. If you like to add this metric, feel free to use the issue from mentioned above.
